spring:
  datasource:
    url: jdbc:mysql://localhost:13306/movie
    username: root
    password: your_password
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true